// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivityGraphController from "./activity_graph_controller"
application.register("activity-graph", ActivityGraphController)

import bridgeSyncController from "./bridge/sync_controller"
application.register("bridge--sync", bridgeSyncController)