// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import bridgeSyncController from "./bridge/sync_controller"
application.register("bridge--sync", bridgeSyncController)

import ReloadController from "./reload_controller"
application.register("reload", ReloadController)
